language: generic
sudo: required
services:
  - docker
env:
  global:
    - SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1

before_install:
  - openssl aes-256-cbc -K $encrypted_0c35eebf403c_key -iv $encrypted_0c35eebf403c_iv -in service-account.json.enc -out service-account.json -d
# Install Google Cloud SDK CLI
  - curl https://sdk.cloud.google.com | bash > /dev/null ;
  - source $HOME/google-cloud-sdk/path.bash.inc
# Configure the SDK
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file service-account.json
  - gcloud config set project multi-k8s-247723
  - gcloud config set compute/zone us-east4-a
  - gcloud container clusters get-credentials multi-cluster
# Login to Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
# Build the 'test' version of our app
  - docker build -t me/react-test -f ./client/Dockerfile.dev ./client

# Run tests
script:
  - docker run -e CI=true me/react-test npm run test -- --coverage

deploy:
  provider: script
  script: bash ./deploy.sh "$DOCKER_USERNAME"
  on:
    branch: master
